data_folder: '/sbgenomics/project-files/DATASET_BUD/'
model_name: 'unetbase-residual-512'
model_type: 'unet'
conf_type: 'train'
batch_size: 16
epoch: 100
model_no: 1
gpu_no: '0'
activation: 'relu'
learning_rate: 0.0001
size_img: 512
scale_factor: 1
thold_tbud: 3
dropout_ratio: 0.5
dropout_level: 0
dir_write: 'outputs/training'