data_folder: '/sbgenomics/project-files/DATASET_BUD/test/'
model_name: 'test'
sample_count: 26
size_img: 512
output_folder: 'output/testing'
trained_model: 'trained_models/unetbase_main_modelCheckpoint.h5'