data_folder: '/sbgenomics/project-files/DATASET_BUD/'
batch_size: 16
epoch: 100
model_no: 1
gpu_no: '0'
model_name: 'unetbase'
learning_rate: 0.001
size_img: 512
scale_factor: 1
dir_write: 'outputs/training'